[build]
  base = "frontend"
  command = "CI=false PUBLIC_URL='' npm run build"
  publish = "frontend/build"

[context.production]
  environment = { SECRETS_SCAN_OMIT_KEYS = "REACT_APP_SUPABASE_URL,REACT_APP_SUPABASE_ANON_KEY" }
